// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentMarkManagement.Entity
{
    public partial class StudentPersonalDetail
    {
        [Key]
        public int Student_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Student_Email { get; set; }
        [Required]
        [StringLength(50)]
        public string Student_Department { get; set; }
        [Required]
        [StringLength(10)]
        public string Gender { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }

        [InverseProperty("Student")]
        public virtual StudentMarkDetail StudentMarkDetail { get; set; }
    }
}