// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace StudentMarkManagement.Entity
{
    public partial class StudentMarkDetail
    {
        [Key]
        public int Student_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Student_Name { get; set; }
        public int Mark_1 { get; set; }
        public int Mark_2 { get; set; }
        public int Total { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        public bool Is_Deleted { get; set; }

        [ForeignKey(nameof(Student_Id))]
        [InverseProperty(nameof(StudentPersonalDetail.StudentMarkDetail))]
        public virtual StudentPersonalDetail Student { get; set; }
    }
}